name: Changelog entry
on:
  pull_request:
    paths:
      - '*.py'
jobs:
  change-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            hasEntry:
              - added: 'changes/*'
      - run: exit $([[ ${{ steps.filter.outputs.hasEntry }} == 'true' ]])
